### ISSUE TITLE
Problem starting the container on Raspberry Pi

### ISSUE THREAD

**Issue by harriv** [philhawthorne/docker-influxdb-grafana#53]
Hi,

I'm poking docker and Influx/Grafana first time on Raspberry Pi. Followed the README, but container wont start:

```
pi@raspi4:~ $ docker start docker-influxdb-grafana
docker-influxdb-grafana
pi@raspi4:~ $ docker ps -a
CONTAINER ID        IMAGE                                          COMMAND             CREATED             STATUS                     PORTS               NAMES
6ce36eebef10        philhawthorne/docker-influxdb-grafana:latest   "/run.sh"           11 minutes ago      Exited (1) 2 seconds ago                       docker-influxdb-grafana
```
Trying with interactive:

```
pi@raspi4:~ $ docker start -i docker-influxdb-grafana
standard_init_linux.go:211: exec user process caused "exec format error"

```
Did I miss something, or should it even work on Raspberry Pi?

**Comment by philhawthorne** [comment]
Hi,

Unfortunately looking at my dockerfile this container most likely won't run on a Raspberry Pi because of architecture issues. However due to the number of writes InfluxDB would make, it may not make sense to run this on a Raspberry Pi with an SD card.

I'll close this issue off for now. I'd be happy to accept a pull request in the future if someone wants to contribute a Raspberry Pi specific dockerfile to support this.

**Comment by harriv** [comment]
@philhawthorne  I don't disagree with the decision or reasoning, but could it be possible to add warning about unsupported architecture? I'm new to docker, so no idea if that's doable. But it would save some time from Raspberry Pi users :)

**Comment by philhawthorne** [comment]
@harriv I can certainly add a warning to this repo's readme 👍 

It won't prevent anyone attempting to run the `docker run` command, but might save someone some time.

**Comment by ronaldn1969** [comment]
@harriv @philhawthorne 
Hi... I build a docker image for my pi with your code and it's running without problems... 

I used git clone and docker build -t

Cheers Ronald
